App/urls.py
from django.urls import path
from . import views
app_name="App"
urlpatterns = [
    path("",views.loginpage,name="loginpage"),
    path("forgotpassword/",views.forgotpassword,name="forgotpassword"),
    path("validateotp/<str:email>/<str:otp>",views.validateOTP,name="validateotp"),
    path("signup/",views.signUp,name="signup"),
    path("dashboard/",views.dashboard,name="dashboard"),
    path("deletepost/<int:post_id>",views.deletePost,name="deletepost"),
    path('like/',views.like,name="like"),
    path("comments/<int:id>",views.comments,name="comments"),
    path("get_comments/<int:id>",views.get_comments,name="getcomments"),
    path("logout",views.logoutuser,name="logout"),
    path("myaccount/",views.myAccount,name='myaccount'),
    path('deleteavatar/',views.deleteavatar,name="deleteavatar"),
]

Coordinator/urls.py
from django.urls import path
from . import views
app_name="Coordinator"
urlpatterns = [
    path("dashboard/",views.dashboard,name="dashboard"),
    path("comments/<int:id>",views.comments,name="comments"),
    path("deletepost/<int:post_id>",views.deletePost,name="deletepost"),
    path("myaccount/",views.myAccount,name='myaccount'),
    path('deleteavatar/',views.deleteavatar,name="deleteavatar"),
    path("setup/",views.setup,name="setup"),
    path("deleteuser/<int:id>",views.deleteuser,name="deleteuser")
]

websavvy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("App.urls"),name="App"),
    path('Coordinator/',include("Coordinator.urls"),name="coordinator")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coordinator/models.py
from django.db import models
import os
# Create your models here.
def csv_path(instance):
    return os.path.join("csvs/{0}".format(instance.doc))


class Csv(models.Model):
    doc = models.FileField(upload_to="csv_path")
    
    def __str__(self):
        return self.doc

    def delete(self,using=None,keep_parents=False):
        self.doc.storage.delete(self.doc.name)
        super().delete()

Coordinator/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.template.loader import render_to_string
from django.utils import html
from App.models import *
from django.contrib import messages
from django.contrib.auth.hashers import check_password,make_password
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .models import *
from django.db import IntegrityError
import csv
from django.core.mail import send_mail
import random
#dependies required for HTML email
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string #This is used for convert the html in to sharable string format
from django.utils.html import strip_tags
#################################

# Create your views here.


@login_required(login_url="App:loginpage")
def dashboard(request):
    user = request.user
    posts = Post.objects.all()
    if(request.method=="POST" or request.FILES):
        
        message = request.POST.get("message")
        images = request.FILES.getlist("images")
        url = request.POST.get("url")
        if(len(message)!=0 or (url is not None) or len(images)!=0):
            if(len(images)==0):
                post = Post(user = user,message=message,url=url)
            else:
                post = Post(user = user,message=message,url=url,image=images[0])
            post.save()
            if(len(images)>1):
                for i in range(1,len(images)):
                    obj = PostImage(msg=post,image=images[i])
                    obj.save()
            print(request.POST.get("postorevent")) 
            if(request.POST.get("postorevent") == "event"):
                print("in")
                title = request.POST.get("title")
                if(title!=""):
                    post.is_event=True
                    post.save()
                    event = Event(title = title,post = post)
                    event.save()
                else:
                    post.delete()
                    messages.error(request,"Event title can't be empty")
        else:
            messages.error(request,"Post can't be empty")
        
        return redirect("Coordinator:dashboard")
    context = {
        "user":user,
        "posts":posts 
    }
    return render(request,"Coordinator/dashboard.html",context)

@login_required(login_url="App:loginpage")
def comments(request,id):
    pass
    try:
        post=Post.objects.get(id=id)
    except:
        return HttpResponse("Something went wrong")
    user=request.user
    comments = Comment.objects.filter(msg=post)
    if(request.method == "POST"):
        message = request.POST.get("message")
        print(message)
        print(type(message))
        if(len(message)!=0):
            comment = Comment(msg = post,user = user,comment = message)
            comment.save()
            return JsonResponse({"result":"success"})
        else:
            messages.error(request,"Post can't be empty")
        
    context = {
        "user":user,
        "post":post,
        "comments":comments
        }
    return render(request,"Coordinator/comments.html",context)

@login_required(login_url="App:loginpage")
def deletePost(request,post_id):
    try:
        post = Post.objects.get(id=post_id)
        if(post.is_event):
            event = Event.objects.get(post=post)
            event.delete()
        # post.delete()
        #the postimage class images are not deleting the while deleting the object of the post so the temporary solution is given here.
        o = PostImage.objects.filter(msg=post_id)
        for i in o:
            i.delete()
        post.delete()
    except:
        pass
    return redirect("Coordinator:dashboard")

@login_required(login_url="App:loginpage")
def myAccount(request):
    pass
    user = request.user
    if(request.method=="POST" or request.FILES):
        pass
        if("firstname" in request.POST):
            firstname = request.POST.get('firstName')
            user.firstName = firstname
            user.save()
        elif("lastname" in request.POST):
            lastname = request.POST.get("lastName")
            user.lastName = lastname
            user.save()
        elif("resetpassword" in request.POST):
            oldpassword = request.POST.get("oldpassword")
            newpassword = request.POST.get("newpassword")
            if(check_password(oldpassword,user.password)):
                user.password=make_password(newpassword)
                user.save()
                logout(request)
                return redirect("App:loginpage")
        elif('changeimage' in request.POST):
            avatar = request.FILES.get("avatar")
            print(avatar)
            user.avatar = avatar
            user.save()
        return redirect("Coordinator:myaccount")
    context={
        "user":user,
    }
    return render(request,"Coordinator/myAccount.html")

@login_required(login_url="App:loginpage")
def deleteavatar(request):
    pass
    user = request.user
    user.avatar = None
    user.save()
    return redirect("Coordinator:myaccount")

@login_required(login_url="App:loginpage")
# Here  admin will upload the pdf of the all the users of the college
def setup(request):
    pass
    users= NewUser.objects.exclude(email="web@gmail.com")
    if(request.method=="POST" or request.FILES):
        if("add by csv" in request.POST):
            pass
            o = Csv(doc = request.FILES.get("doc"))
            o.save()
            with open(o.doc.path,'r') as f:
                reader = csv.reader(f)
                count=0
                for i,row in enumerate(reader):
                    if(i==0):
                        pass
                    else:
                        try:
                            password = generatePassword()
                            user = NewUser(email = row[0],roll = row[1],firstName=row[2],lastName = row[3],password=make_password(password))
                            user.save()
                            count+=1
                            ##------------------Sending Email -------------------------------
                            html_content = render_to_string("Coordinator/logininvite.html",{"email":user.email,"password":password,"name":user.get_fullname()})
                            text_content = strip_tags(html_content)
                            email_obj = EmailMultiAlternatives(
                                #subject
                                "Websavvy|Invitation",
                                #content
                                text_content,
                                #from email
                                "websavvy.info@gmail.com",
                                #to email
                                [user.email]
                            )
                            email_obj.attach_alternative(html_content,"text/html")
                            email_obj.send()
                            #----------------------------------------------------------------
                        except:
                            messages.error(request,"Error occured while creating an user of email "+row[0])
            o.delete()
            if(count!=0):
                messages.success(request,"Total "+str(count)+" users have been created")
            return redirect("Coordinator:setup")
        elif("individual" in request.POST):
            email = request.POST.get("email")
            roll = request.POST.get("roll")
            firstName = request.POST.get("firstname")
            lastName = request.POST.get("lastname")
            isCoordinator = request.POST.get("iscoordinator")
            try:
                if(isCoordinator =="on"):
                    user = NewUser(email = email,roll= roll,firstName=firstName,lastName=lastName,isCoordinator=True)
                else:
                    user = NewUser(email = email,roll= roll,firstName=firstName,lastName=lastName)
                password=generatePassword()
                user.password=make_password(password)
                user.save()
                ##------------------Sending Email -------------------------------
                html_content = render_to_string("Coordinator/logininvite.html",{"email":user.email,"password":password,"name":user.get_fullname()})
                text_content = strip_tags(html_content)
                email_obj = EmailMultiAlternatives(
                    #subject
                    "Websavvy|Invitation",
                    #content
                    text_content,
                    #from email
                    "websavvy.info@gmail.com",
                    #to email
                    [user.email]
                )
                email_obj.attach_alternative(html_content,"text/html")
                email_obj.send()
                #----------------------------------------------------------------
                messages.success(request,"The user created successfully")
            except IntegrityError:
                messages.error(request,"The user with email "+email+" already exists")
            finally:
                return redirect("Coordinator:setup")



    return render(request,"Coordinator/setup.html",{"users":users})

def generatePassword():
    series = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    password = "".join(random.sample(series,6))    
    return password


def deleteuser(request,id):
    pass
    
    try:
        user = NewUser.objects.get(id=id)
        for i in Post.objects.filter(user=user):
            for j in PostImage.objects.filter(msg=i):
                j.delete()
            i.delete()
        user.delete()
        messages.success(request,"User is deleted")
    except:
        messages.error(request,"Something went wrong please try again")
    return redirect("Coordinator:setup")

Coordinator/templates/Coordinator/logininvite.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" , initial-scale=1>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

</head>

<body style="
  font-family: 'Trebuchet MS', sans-serif; 
  font-size: 16px;
  background: white;
background: linear-gradient(132deg, rgba(241,246,10,0.3533788515406162) 0%, rgba(226,22,191,0.20772058823529416) 100%);
height: 100%;
  ">

    <div style="padding-left:3%; padding-right: 3%">

        <h5 style="text-align: left; font-size: 12px;">Dear {{name}},</h5>
        <h5 style="text-align: left; font-size: 12px;">Here are your login details:</h5>
        <p style="font-size: 12px;">UserName : <b style="color:purple">{{email}}</b><br>
            Password : <b style="color:purple">{{password}}</b><br><span style="font-size: 12px;">You can change your
                password by logining into
                WEBSAVVY</span>:<span
                style="color: rgba(4, 48, 241, 0.863); font-size: 12px;">https://www.websavvy.com</span></p>



        <center><img width="95%" src="https://i.ibb.co/4pfdWNw/mail-poster-2-1.jpg" /></center>
        <div style="text-align: right">
            <p style="font-size: 12px;">Thank you</p>
            <p style="font-size: 12px;">Websavvy</p>
        </div>
    </div>

</body>

</html>

Coordinator/templates/Coordinator/setup.html
<!doctype html>
{% load static %}
{% load customtags %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'Coordinator/css/setup.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a81368914c.js"></script>
  <title>WebSavvy|SetUp</title>
</head>

<body>
  <nav class="navbar sticky-top navbar-light bg-light">
    <a href="{% url 'Coordinator:dashboard' %}" class="navbar-brand mb-0 h1" style="color: white;"> &nbsp; WebSavvy</a>
    <span class="navbar-text">
      <button class="btn btn-outlinel-light textdark">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell"
          viewBox="0 0 16 16">
          <path
            d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"
            fill="white" />
        </svg>
      </button>
    </span>
  </nav>

  <div class="conatiner">
    {% for i in messages %}
    {% if i.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
      {{i}}
    </div>
    {% endif %}
    {% if i.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">{{i}}</div>
    {% endif %}
    {% endfor %}
    <div class="row">
      <div class="col-lg-3">

      </div>
      <div class="col-lg-6">
        <div class="card mt-3">
          <div class="card-header" style="background-color: rgb(245, 227, 248);">
            <b>SetUp</b>
          </div>
          <div class="card-body">
            <span style="font-size: 12px; color:rgb(106, 106, 119)">You can all the memebers of the club in a single go
              by giving data in csv fomat(specified format only)</span>
            <hr>
            <div style="margin:2%">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="add by csv" hidden />
                <input type="file" name="doc" id="file" onchange="return fileValidation()" required />
                <button class="btn1 btn-success" type="submit">Submit</button>
              </form>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <div class="card-header" style="background-color: rgb(245, 227, 248);">
            <b>Add individual</b>
          </div>
          <div class="card-body">
            <span style="font-size: 12px; color:rgb(106, 106, 119)">You can and individual student here.</span>
            <hr>
            <div style="margin: 2%;">

              <form method="POST">
                {% csrf_token %}
                <div class="form-row">
                  <input name="individual" hidden />
                  <div class="form-group col-md-6">
                    <label for="firstname">FirstName</label>
                    <input type="text" class="form-control" id="firstname" name="firstname" required>
                  </div>
                  <div class="form-group col-md-6">
                    <label for="lastname">LastName</label>
                    <input type="text" class="form-control" id="lastname" name="lastname" required>
                  </div>
                  <div class="form-group col-md-6">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                  </div>
                  <div class="form-group col-md-6">
                    <label for="roll">Roll</label>
                    <input type="text" class="form-control" id="roll" name="roll" required>
                  </div>
                </div>
                <div class="form-group">
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="gridCheck" name="iscoordinator">
                    <label class="form-check-label" for="gridCheck">
                      Is Coordinator
                    </label>
                  </div>
                </div>
                <button type="submit" class="btn2 btn-primary">Add User</button>
              </form>
            </div>

          </div>
        </div>
      </div>
    </div>



  </div>

  <center>
    <h5 class="m-3">List of Users</h5>
  </center>
  <center>
    <div class="container-fluid mt-2">
      <table class="table table-striped table-bordered">
        <center>
          <thead class="thead-light">

            <tr>

              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Roll</th>
              <th scope="col">#</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}<tr>
              {% if user.isCoordinator %}<td>{{user.get_fullname}} <svg xmlns="http://www.w3.org/2000/svg" width="14"
                  height="14" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                  <path fill="purple" d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                  <path fill="purple"
                    d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                </svg></td>{% else %}<td>{{user.get_fullname}}</td>{% endif %}
              <td>{{user.email}}</td>
              <td>{{user.roll}}</td>
              <td><button type="button" class="btn btn-outline-light" data-toggle="modal"
                  data-target="#delete{{user.id}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                    fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path fill="red"
                      d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                  </svg></button></td>
            </tr>
            <div class="modal fade" id="delete{{user.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1"
              aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Delete User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p style="color:grey">Are you sure you want to delete this user</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-success"><a href="{% url 'Coordinator:deleteuser' user.id %}"
                        class="text-decoration-none text-light">Yes</a></button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

          </tbody>
        </center>
      </table>
    </div>
  </center>
  <script>
    function fileValidation() {
      var fileInput =
        document.getElementById('file');

      var filePath = fileInput.value;

      // Allowing file type
      var allowedExtensions =
        /(\.csv)$/i;

      if (!allowedExtensions.exec(filePath)) {
        alert('Selected file not in a csv format');

        fileInput.value = '';
        return false;
      }
    }
  </script>





  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
</body>

</html>