App/urls.py
from django.urls import path
from . import views
app_name="App"
urlpatterns = [
    path("",views.loginpage,name="loginpage"),
    path("forgotpassword/",views.forgotpassword,name="forgotpassword"),
    path("validateotp/<str:email>/<str:otp>",views.validateOTP,name="validateotp"),
    path("signup/",views.signUp,name="signup"),
    path("dashboard/",views.dashboard,name="dashboard"),
    path("deletepost/<int:post_id>",views.deletePost,name="deletepost"),
    path('like/',views.like,name="like"),
    path("comments/<int:id>",views.comments,name="comments"),
    path("get_comments/<int:id>",views.get_comments,name="getcomments"),
    path("logout",views.logoutuser,name="logout"),
    path("myaccount/",views.myAccount,name='myaccount'),
    path('deleteavatar/',views.deleteavatar,name="deleteavatar"),
]

websavvy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("App.urls"),name="App"),
    path('Coordinator/',include("Coordinator.urls"),name="coordinator")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/templates/App/OTP.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" , initial-scale=1>

    <!-- Bootstrap CSS -->
    <link rel=" stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <style type="text/css">
        body {
            font-family: "Poppins", sans-serif;
            vertical-align: center;
        }
    </style>

</head>

<body>


    <h5>Dear {{name}},</h5>
    <h5>Here is your OTP to reset password:</h5>
    <center>
        <h1 style="color:purple">{{otp}}</h1>
    </center>
    <img src="{% static 'App/images/defaultavatar' %}" />
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
</body>

</html>

App/templates/App/forgotpassword.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'App/css/forgot.css' %}">
    <title>Document</title>
</head>

<body>
    <img class="bg4" src="{% static 'App/images/team10.svg' %}">
    <center>
        <div class="container">
            <div class="card-body">
                <h2>Forgot Password</h2>
                <p>Enter the email address through which you have registered with the application.</p>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="#email"></label>
                        <input type="email" name="email" id="email" placeholder="Enter your mail Id"
                            class="form-control" required>
                        <button id="submit_button" type="submit" class="btn1"
                            onclick="document.getElementById('submit_button').type='none'">SUBMIT</button>
                    </div>
                </form>

            </div>
        </div>
    </center>
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger text-center m-3" role="alert">
        {{message}}
    </div>
    {% endif %}
    {% endfor %}
</body>

</html>

App/templates/App/loginpage.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <title>WebSavvy | Login</title>
  <link rel="stylesheet" type="text/css" href="{% static 'App/css/loginpage.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a81368914c.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <img class="bg1" src="{% static 'App/images/team8.jpg' %}">



  <div class="grid1">
    <div class="pic">
      <img class="bg2" src="{% static 'App/images/team5.svg' %}">

    </div>
    <div class="container">
      <div class="header">
        <div class="header-image">
          <div class="header-image-particle header-image-particle-1"></div>
          <div class="header-image-particle header-image-particle-2"></div>
          <div class="header-image-particle header-image-particle-3"></div>
          <svg viewBox="0 0 1000 1000">
            <g transform="translate(0.000000,512.000000) scale(0.100000,-0.100000)">
              <path
                d="M2901.7,4280.3c-1274.3-463.7-2048.5-755-2075.3-779.9c-80.5-74.7-99.7-139.9-128.4-448.4c-172.5-1849.2-9.6-3437.8,482.9-4691.1c210.8-538.5,527-1086.5,858.5-1494.7c298.9-367.9,760.8-776.1,1159.4-1025.2c553.8-346.8,1337.6-617,1791.7-620.9c486.8-3.8,1339.5,302.8,1916.3,687.9c550,367.9,1046.3,881.5,1420,1469.8C9187.2-1263.6,9524.4,689.2,9302.1,3052c-28.8,308.5-47.9,373.7-128.4,448.4C9118.2,3554,5078.6,5020,4994.3,5020C4959.8,5018.1,4018.9,4686.6,2901.7,4280.3z M6878,3705.4l1810.9-657.3l23-274c61.3-737.8,51.7-1690.2-24.9-2343.6c-191.6-1684.4-812.5-2977.9-1807.1-3779c-492.5-394.7-1145.9-701.4-1711.3-801c-182.1-32.6-189.7-32.6-390.9,7.7c-1293.5,260.6-2380,1203.4-2964.5,2569.8c-276,649.6-442.7,1368.2-534.7,2309.1c-32.6,331.5-28.7,1646.1,5.8,2027.4l26.8,283.6l1839.6,668.8c1167,423.5,1853.1,665,1878,657.3C5049.9,4368.5,5881.5,4067.6,6878,3705.4z" />
              <path
                d="M4430.9,2691.7c-298.9-80.5-532.7-297-642-596c-36.4-103.5-42.2-159-49.8-663l-7.7-551.9h-86.2c-47.9,0-122.6-9.6-166.7-23c-105.4-30.7-264.5-189.7-295.1-295.1c-32.6-113.1-32.6-2010.2,0-2123.3c30.7-105.4,189.7-264.5,295.1-295.1c113.1-32.6,2930-32.6,3043.1,0C6627-1825,6786-1666,6816.7-1560.6c32.6,113.1,32.6,2010.2,0,2123.3C6786,668.1,6627,827.1,6521.6,857.8c-44.1,13.4-118.8,23-166.7,23h-86.2l-7.7,551.9c-7.7,504-13.4,559.6-49.8,663c-111.1,302.8-344.9,517.4-649.6,596C5410.1,2731.9,4576.5,2730,4430.9,2691.7z M5513.6,2053.6c122.7-88.2,128.4-113.1,134.1-668.8l5.7-504H5002h-653.5V1356c1.9,576.8,17.2,640.1,178.2,720.5c51.7,26.8,128.4,30.7,492.5,26.8C5437,2097.6,5452.3,2095.7,5513.6,2053.6z M5210.8,202.4c199.3-132.2,228-415.8,55.6-588.3l-74.7-74.7v-371.8c0-444.6,3.8-433.1-191.6-433.1c-195.5,0-191.6-11.5-191.6,433.1v371.8l-74.7,74.7c-153.3,153.3-155.2,385.2-1.9,538.5c42.2,42.2,103.5,84.3,138,93.9C4971.3,277.2,5128.4,258,5210.8,202.4z" />
            </g>
          </svg>
        </div>

        <h1 class="header-title text-center" style="color:rgb(255, 225, 253);">
          Welcome to <b>WEBSAVVY!</b>
        </h1>

        <p class="text text-center">LOGIN </p>
      </div>
      <form method="POST" autocomplete="off">
        <center>

          {% csrf_token %}
          <div class="input app-input">
            <input type="text" name="email" id="email" placeholder="Email" />
            <label for="email"></label>
          </div>

          <div class="input app-input">
            <input type="password" name="password" id="password" placeholder="password" />
            <label for="password"></label>
          </div>

        </center>
        <input type="submit" id="submit" hidden />
      </form>
      <div>
        <a href="{% url 'App:forgotpassword' %}"
          style="font-size: 12px; float:right; text-decoration: none; margin-right: 40px; color: rgb(0, 0, 0);">Forgot
          Password?</a>
      </div>
      <div>
        <center>
          <button type="button" onclick="document.getElementById('submit').click()" class="button app-login-button">
            SUBMIT
          </button>
        </center>

      </div>

    </div>

  </div>
  <img class="bg3" src="{% static 'App/images/team18.jpg' %}">
  <img class="bg4" src="{% static 'App/images/team5.svg' %}">





  <script>
    const modal = document.querySelector(".app-modal");

    modal.addEventListener("click", (event) => {
      const modalBody = document.querySelector(".app-modal-body");
      const isBackdropElemClick = !modalBody.contains(event.target);

      if (isBackdropElemClick) {
        toggleClass(modal, "modal-active");
      }
    });

    const loginButton = document.querySelector(".app-login-button");
    const saveButton = document.querySelector(".app-save-button");
    const modalButtons = [saveButton, loginButton];

    modalButtons.forEach((button) => {
      button.addEventListener("click", () => {
        toggleClass(modal, "modal-active");
      });
    });

    const settingsButtons = document.querySelectorAll(".app-settings-button");

    settingsButtons.forEach((button) => {
      button.addEventListener("click", () => {
        const icon = button.parentNode.querySelector(
          ".app-settings-button-icon"
        );

        toggleClass(button, "settings-button-active");
        toggleClass(icon, "settings-button-icon-active");
      });
    });

    const inputContainers = document.querySelectorAll(".app-input");

    inputContainers.forEach((container) => {
      const input = container.querySelector("input");
      const events = ["focus", "blur"];

      events.forEach((event) => {
        input.addEventListener(event, () => {
          if (!input.value) {
            toggleClass(container, "input-active");
          }
        });
      });
    });

    function toggleClass(element, className) {
      const isActive = element.classList.contains(className);

      if (isActive) {
        element.classList.remove(className);
      } else {
        element.classList.add(className);
      }
    }


  </script>


</body>

</html>

App/templates/App/passwordchanged.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'App/css/passwordchanged.css' %}">
    <title>passwordchanged</title>
</head>

<body>
    <img class="bg" src="{% static 'App/images/team10.svg' %}">
    <center>
        <div class="container">
            <p>Your password has successfully changed. Go back to the <a href="{% url 'App:loginpage' %}"
                    style="color: rgb(163, 9, 198); font-size: 20px;"> loginpage </a></p>
        </div>
    </center>




</body>

</html>

App/templates/App/signup.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>SignUp</title>
</head>

<body>
    <h1>SignUp</h1>
    <form method="POST">
        {% csrf_token %}
        email : <input type="email" name="email" />
        roll : <input type="text" name="roll" />
        firstName : <input type="text" name="fn" />
        lastName : <input type="text" name="ln" />
        password : <input type="password" name="password">
        conform password : <input type="password" name="conformpassword" />
        <input type="submit" />
    </form>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
</body>

</html>

App/templates/App/validation.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'App/css/validation.css' %}">
    <title>Validate OTP</title>
</head>

<body>
    <img class="bg4" src="{% static 'App/images/team10.svg' %}">
    <center>
        <div class="container">
            <p>An OTP for changing password have been sent to the corresponding Email Address</p>
            <center>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="#otp"></label>
                        <input type="text" id="otp" class="form-control" placeholder="OTP" name="otp" required />
                        <label for="p1"></label>
                        <input type="password" id="p1" class="form-control" placeholder="New Password" name="p1"
                            required />
                        <label for="p2"></label>
                        <input type="password" id="p2" class="form-control" placeholder="Confirm Password" name="p2"
                            required />
                        <p id="error" style="display:none; color:red; font-size: 10px; ">Password and conform need to be
                            same</p>
                        <button id="submit_button" type="button" class="btn" onclick="func()">SUBMIT</button>
                        <input id="submit" type="submit" hidden />
                    </div>
                </form>
            </center>

        </div>


        <script>
            var p1 = document.getElementById("p1")
            var p2 = document.getElementById("p2")
            var btn = document.getElementById("submit_button")
            var error = document.getElementById("error")
            function func() {
                if (p2.value != "") {
                    if (p1.value != p2.value) {
                        error.style.display = "block";
                    } else {
                        error.style.display = "none";
                        document.getElementById("submit").click()
                        document.getElementById("submit").type = "none"
                    }
                }
            }
        </script>

</body>

</html>